sudo: required
language: php
dist: trusty

php:
  - 7.1
  - 7.2

env:
  global:
    - setup=basic

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux

script: vendor/bin/phpunit --testdox
